# Deployment Details
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
# Deployment label  
    app: currency-exchange
  name: currency-exchange
  namespace: default
# Pod Specification  
spec:
# How many pods?
  replicas: 2
  selector:
    matchLabels:
 # This label is defined below  and matches the deployment to all the pods withthe specified label 
      app: currency-exchange
  strategy:
 # Release strategy is specified here. 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
       labels:
# Pod label       
        app: currency-exchange
# Container Specification ( A Pod an contain multiple containers)        
    spec:
      containers:
# Container 1      
      - image: mailsonymathew/mmv2-docker-currency-exchange-service-kubernetes:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-docker-currency-exchange-service-kubernetes
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
# Optional: To see autoscaling in action , we need to specify the amount of CPU reserved for this resource             
        resources:
          requests:
            cpu: "250m"                    
# Container 2      
#      - image: mailsonymathew/mmv3-docker-currency-exchange-service-kubernetes:0.0.11-SNAPSHOT
#        imagePullPolicy: IfNotPresent
#        name: mmv3-docker-currency-exchange-service-kubernetes
# Container 3      
#      - image: mailsonymathew/mmv3-docker-currency-exchange-service-kubernetes:0.0.11-SNAPSHOT
#        imagePullPolicy: IfNotPresent
#        name: mmv3-docker-currency-exchange-service-kubernetes                  
      restartPolicy: Always
---
# Service Details
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
# Service specification matches the service to a specific deployment  
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
# Can be used for web api's where al lrequests need to be send to the same instance. Here since we are using REST api's this does nto matter.    
  sessionAffinity: None
# Type of the service  
  type: LoadBalancer