version: '3.8'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev:latest  # landoop already has a lot of connectors loaded onto their kafka cluster image
    #image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.65.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    # The network being used by all containers. This NW is defined towards the end.       
    networks:
      -  kafka-network  
    volumes:
    # The connector plugin iss downoloaded to D:\OneDrive\Study\DevOps\Kafka\ApacheKafkaConnect\Code\docker-compose-other-versions\jcustenborder-kafka-connect-twitter-0.3.34.
    # We map the above location to to the following volume D:\OneDrive\Study\DevOps\Kafka\ApacheKafkaConnect\Code\docker-compose-other-versions\connectors\jcustenborder-kafka-connect-twitter-0.3.34
      - ./jcustenborder-kafka-connect-twitter-0.3.34:/connectors/jcustenborder-kafka-connect-twitter

  # we will use elasticsearch as one of our sinks.
  # This configuration allows you to start elasticsearch
  elasticsearch:
    image: itzg/elasticsearch:2.4.3
    environment:
      PLUGINS: appbaseio/dejavu
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
    ports:
      - "9200:9200"
    # The network being used by all containers. This NW is defined towards the end.
    networks:
      -  kafka-network
# The dependency of the container on any other       
    depends_on:
      - kafka-cluster
                
      

  # we will use postgres as one of our sinks.
  # This configuration allows you to start postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
    # The network being used by all containers. This NW is defined towards the end.
    networks:
      -  kafka-network
# The dependency of the container on any other       
    depends_on:
      - kafka-cluster

# Networks to be created to facilitate communication between containers
networks:
  kafka-network: